config/routes.rb
Rails.application.routes.draw do

  root 'bienvenido#aboutus'

  get 'bienvenido/aboutus'

  get 'bienvenido/contacto'

  get 'bienvenido/salon'

  get 'bienvenido/bano'

  get 'bienvenido/cocina'

  get 'bienvenido/legal'

  get 'bienvenido/support'

  resources :tasks

  resources :users do
    resources :photos
  end

  resources :search do
    resources :users
  end

  resources :products do
      resources :comments
      resources :sales do
        get 'recent', on: :collection
      end
     end

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
	layout 'layouts/bienvenido', except: ['aboutus']


def floor_u
end

  def aboutus
  end

  def legal
  end

  def support
  end

  def salon
  end

  def baño
  end

  def cocina
  end

  def contacto
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
<<<<<<< Updated upstream
=======
  layout 'bienvenido'
>>>>>>> Stashed changes

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @task.description = 'Pon la descripcion aqui'
    @task.status = :true
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
        format.js {  render :create }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
      format.js { render :destroy }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/bienvenido/aboutus.html.erb
<<<<<<< Updated upstream
<% content_for :carrusel do %>

      <div class="row">
        <div class="large-12 columns">

          <ul class="example-orbit" data-orbit>
  <li>
    <img src="http://www.i-decoracion.com/Uploads/i-decoracion.com/ImagenesGrandes/decoracion-japonesa-9.jpg" alt="slide 1" />
    <div class="orbit-caption">
      Caption One.
    </div>
  </li>
  <li class="active">
    <img src="http://www.decorablog.com/wp-content/2014/06/Salones-minimalistas18.jpg" alt="slide 2" />
    <div class="orbit-caption">
      Caption Two.
    </div>
  </li>
  <li>
    <img src="http://www.decopasion.com/Imagenes/decoracion-mediterranea.jpg" alt="slide 3" />
    <div class="orbit-caption">
      Caption Three.
    </div>
  </li>
</ul>
      
        </div>




        
        <hr/>
        </div>

<% end %>



=======

        <div class="large-12 columns">
          <img src="/FOTOWG.jpg"/>
        </div>
        
>>>>>>> Stashed changes

app/views/bienvenido/bano.html.erb
<div class="row">
        <div class="large-4 columns">
          <img src="/baño1.jpg"/>
         
        </div>
        
        <div class="large-4 columns">
          <img src="/baño2.jpg"/>
     
        </div>
        
        <div class="large-4 columns">
          <img src="/baño3.jpg"/>
          <h4>  </h4>
      
        </div>
      
        </div>

        <div class="row">
        <div class="large-4 columns">
          <img src="/baño4.jpg"/>
         
        </div>
        
        <div class="large-4 columns">
          <img src="/baño5.jpg"/>
     
        </div>
        
        <div class="large-4 columns">
          <img src="/baño6.jpg"/>
          <h4>  </h4>
      
        </div>
      
        </div>

app/views/bienvenido/cocina.html.erb
<div class="row">
        <div class="large-4 columns">
          <img src="/cocina1.jpg"/>
         
        </div>
        
        <div class="large-4 columns">
          <img src="/cocina2.jpg"/>
     
        </div>
        
        <div class="large-4 columns">
          <img src="/cocina3.jpg"/>
          <h4>  </h4>
      
        </div>
      
        </div>

        <div class="row">
        <div class="large-4 columns">
          <img src="/cocina4.jpg"/>
         
        </div>
        
        <div class="large-4 columns">
          <img src="/cocina5.jpg"/>
     
        </div>
        
        <div class="large-4 columns">
          <img src="/cocina6.jpg"/>
          <h4>  </h4>
      
        </div>
      
        </div>

app/views/bienvenido/contacto.html.erb
<h1 class="centrado">flooru@gmail.com</h1>
<h4 class="centrado"> Escríbenos y síguenos en las redes socailes</h4>

<div class="large-12 columns">
          <img src="/FOTOWG.jpg"/>
        </div>
 
 

app/views/bienvenido/floor_u.html.erb
<h1>hola floor u</h1>

app/views/bienvenido/legal.html.erb
<h1>Bienvenido#legal</h1>
<p>Find me in app/views/bienvenido/legal.html.erb</p>

app/views/bienvenido/salon.html.erb
<div class="row">
        <div class="large-4 columns">
          <img src="/salon6.jpg"/>
         
        </div>
        
        <div class="large-4 columns">
          <img src="/salon1.jpg"/>
     
        </div>
        
        <div class="large-4 columns">
          <img src="/salon2.jpg"/>
          <h4>  </h4>
      
        </div>
      
        </div>

        <div class="row">
        <div class="large-4 columns">
          <img src="/salon3.jpg"/>
         
        </div>
        
        <div class="large-4 columns">
          <img src="/salon4.jpg"/>
     
        </div>
        
        <div class="large-4 columns">
          <img src="/salon5.jpg"/>
          <h4>  </h4>
      
        </div>
      
        </div>

app/views/bienvenido/support.html.erb
<h1>Bienvenido#support</h1>
<p>Find me in app/views/bienvenido/support.html.erb</p>

app/views/layouts/_bienvenido_footer.html.erb
      <footer class="row">
        <div class="large-12 columns">
          <hr/>
          <div class="row">
            <div class="large-6 columns">
              <p>© Copyright no one at all. Go to town.</p>
            </div>
            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="#">Link 1</a></li>
                <li><a href="#">Link 2</a></li>
                <li><a href="#">Link 3</a></li>
                <li><a href="#">Link 4</a></li>
              </ul>
            </div>
          </div>
        </div> 
      </footer>

app/views/layouts/_bienvenido_header.html.erb
<div class="row">
        <div class="large-6 columns">
          <h1><img width="400px" src="/floor-u.png"/></h1>
        </div>
        <div class="large-6 columns">
          <ul class="right button-group">
          <li><a href="http://iconosquare.com/wendyss9" class="button"><img width="25" src="https://lh3.ggpht.com/vFpQP39LB60dli3n-rJnVvTM07dsvIzxrCL5xMiy1V4GV4unC1ifXkUExQ4N-DBCKwI=w300"></a></li> 
          <li><a href="http://www.facebook.com/wendy.stuyck" class="button"><img width="25" src="http://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/F_icon.svg/2000px-F_icon.svg.png"></a></li>
          <li><a href="http://www.twitter.com/gfernandez15" class="button"><img width="25" src="http://www.h3dwallpapers.com/wp-content/uploads/2014/11/Twitter_logo_png-4.png"></a></li>
          <li><a href="https://plus.google.com/108410067964288375075/posts" class="button"><img width="25" src="http://upload.wikimedia.org/wikipedia/commons/0/04/Google_Plus_logo.png"></a></li>
          </ul>
         </div>
       </div>

<<<<<<< Updated upstream
 <div class="row">
        <div class="medium-3 large-3 text-center columns">
          <img width="180" src="http://mobleslera.hol.es/wp-content/flagallery/catalogo-2014-salon/salon-ordenado7.jpg">
            <h4><%= link_to 'Salón', bienvenido_salon_path %></h4>


        </div>
        <div class="medium-3 large-3 text-center column">
          <img width="160" src="http://www.i-banos.com/Imagenes/bano-con-distribucion-feng-shui.jpg">
          
            <h4><%= link_to 'Baño', bienvenido_bano_path %></h4>
          
        </div>
        <div class="medium-3 large-3 text-center column">
          <img width="150" src="http://www.elmueble.com/medio/2012/12/12/cocina_con_pared_marron_hacia_la_ventana_1280x1164.jpg">
        

            <h4><%= link_to 'Cocina', bienvenido_cocina_path %></h4>
            
        </div>
        <div class="medium-3 large-3 text-center column">
          <img width="180" src="http://img.decorailumina.com.s3.amazonaws.com/wp-content/uploads/2013/01/decorar-dormitorio-matrimonial-8.jpg">
            <h4>Dormitorio</h4>
            
        </div>
      </div>
=======
 <div class="large-6 columns">
          <ul class="right button-group">
          <li><a href="http://iconosquare.com/wendyss9" class="button"><img width="20" large-6 src="https://lh3.ggpht.com/vFpQP39LB60dli3n-rJnVvTM07dsvIzxrCL5xMiy1V4GV4unC1ifXkUExQ4N-DBCKwI=w300"></a></li> 
          <li><a href="http://www.facebook.com/wendy.stuyck" class="button"><img width="25" src="http://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/F_icon.svg/2000px-F_icon.svg.png"></a></li>
          <li><a href="http://www.twitter.com/gfernandez15" class="button"><img width="25" src="https://g.twimg.com/Twitter_logo_blue.png"></a></li>
          <li><a href="#" class="button">Link 4</a></li>
          </ul>
         </div>
       </div>
>>>>>>> Stashed changes

app/views/layouts/_blog_aside.html.erb
        <aside class="large-3 columns">
     
          <h5>Categories</h5>
          <ul class="side-nav">
            <li><a href="#">No</a></li>
            <li><a href="#">Elimina</a></li>
          s
          </ul>
     
          <div class="panel">
            <h5>Featured</h5>
            <p>Si quieres compartir tu opinión con nosotros, no lo dudes</p>
            <a href="#">Mostrar→</a>
          </div>
     
        </aside>s

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Appdemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'vendor/modernizr', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html> 

app/views/layouts/bienvenido.html.erb
<!DOCTYPE html>
<html>
<head>

  
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Appdemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'vendor/modernizr', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/bienvenido_header'%>
<<<<<<< Updated upstream
=======
     
      <div class="row">
        <div class="large-12 columns">

          <ul class="example-orbit" data-orbit>
  <li>
    <img src="http://www.i-decoracion.com/Uploads/i-decoracion.com/ImagenesGrandes/decoracion-japonesa-9.jpg" alt="slide 1" />
    <div class="orbit-caption">
      Caption One.
    </div>
  </li>
  <li class="active">
    <img src="http://www.decorablog.com/wp-content/2014/06/Salones-minimalistas18.jpg" alt="slide 2" />
    <div class="orbit-caption">
      Caption Two.
    </div>
  </li>
  <li>
    <img src="http://www.decopasion.com/Imagenes/decoracion-mediterranea.jpg" alt="slide 3" />
    <div class="orbit-caption">
      Caption Three.
    </div>
  </li>
</ul>
      
        </div>
>>>>>>> Stashed changes



<%= yield :carrusel%>

      </div>
      
     
     
      <div class="row">
      	<%= yield %>

   <%= link_to "Comenta", new_task_path, remote: :true, class: "button sucess small" %>     
   <div id="new_task"></div>
   

   <%= link_to "VER COMENTARIOS", tasks_path %>    
       

        </div>
        


    <div class="row">
        <div class="large-12 columns" >
        
          <div class="panel" style="margin-top:10px;">
            <h4>¿Necesitas ayuda?</h4>
                
            <div class="row">
              <div class="large-9 columns">
                <p>Floor-u te ofrece  un servicio de atención al cliente lo más efectivo posible. Mándanos un correo y te responderemos en la mayor brevedad posible. Gracias ¡Pincha en contacto!</p>
              </div>
              <div class="large-3 columns">
<<<<<<< Updated upstream
                <%= link_to 'Contacto', bienvenido_contacto_path, class: "radius button right" %> 


            
=======
                <%= link_to 'Contacto', bienvenido_aboutus_path, class: "radius button right" %>
              
>>>>>>> Stashed changes


              </div>
            </div>
          </div>
          
        </div>
      </div>       
      
<%= render 'layouts/bienvenido_footer'%>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html> 

app/views/tasks/_create.html.erb
      <tr id="task<%=@task.id%>">
        <td><%= @task.description %></td>
        <td><%= @task.status %></td>
        <td><%= link_to 'Muestra', @task %></td>
        <td><%= link_to 'Edita', edit_task_path(@task) %></td>
        <td><%= link_to 'Elimina', @task, remote: :true, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/tasks/_form.html.erb
<%= form_for(@task, remote: :true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_new.html.erb
<h1>Nuevo comentario</h1>
<%= render 'form' %>

app/views/tasks/create.js.erb
$('#new_task').empty()
$('table tbody').append('<%= escape_javascript( render 'create')%>')

app/views/tasks/destroy.js.erb
$('#task<%=@task.id%>').toggle('highlight')
$('#task<%=@task.id%>').remove()

app/views/tasks/edit.html.erb
<h1>Edita tu comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div id="new_task">
</div>

<h1>COMENTA</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr id="task<%=task.id%>">
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, remote: :true, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<h1>Añade nuevo comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('#new_task').html('<%= escape_javascript(render 'new') %>');
$('#new_task').slidedown(350);

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>